### ISSUE TITLE
Crash server (JSON_Stringify, JSON_SaveFile) [Linux

### ISSUE THREAD

**Issue by continue98** [Southclaws/pawn-json#9]
Hi, crash server with JSON_Stringify. Code: 

```
// global var
new Node: g_node_leaders_list_json = Node:-1;

// some SA-MP callback (for example OnPlayerConnect)

```
static buf[82_000];
if (JSON_Stringify(g_node_leaders_list_json, buf) == 0)
{
    // useful logic
}
buf[0] = '\0';
```

```
// in main/OnGameModeInit
```
g_node_leaders_list_json = JSON_Object();
JSON_SetArray(g_node_leaders_list_json, "leaders", JSON_Array());
JSON_ArrayAppend(g_node_leaders_list_json, "leaders", JSON_Object(
    "fraction_id", JSON_Int(f_info[i][f_id]),
    "fraction_name", JSON_String(f_info[i][f_name]),
    "fraction_leader_name", JSON_String(f_info[i][f_leader_name])
    )
);
```

Stracktrace: 

```
Thread 1 "samp03svr" received signal SIGSEGV, Segmentation fault.
0xf596fe12 in hashbrown::raw::sse2::Group::load () at /cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/src/raw/sse2.rs:50
50      /cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/src/raw/sse2.rs: No such file or directory.
(gdb) bt 10
#0  0xf596fe12 in hashbrown::raw::sse2::Group::load ()
    at /cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/src/raw/sse2.rs:50
#1  hashbrown::raw::RawTableInner<alloc::alloc::Global>::find_inner<alloc::alloc::Global> (self=0x81ffbec,
    hash=3136313669715300515, eq=...)
    at /cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/src/raw/mod.rs:1174
#2  0xf5969304 in hashbrown::raw::RawTable<(samp::amx::AmxIdent, samp_sdk::amx::Amx), alloc::alloc::Global>::find<(samp::amx::AmxIdent, samp_sdk::amx::Amx), alloc::alloc::Global, hashbrown::map::equivalent_key::{closure_env#0}<samp::amx::AmxIdent, samp::amx::AmxIdent, samp_sdk::amx::Amx>> (self=0x81ffbec, hash=3136313669715300515, eq=...)
    at /cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/src/raw/mod.rs:816
#3  0xf5969248 in hashbrown::raw::RawTable<(samp::amx::AmxIdent, samp_sdk::amx::Amx), alloc::alloc::Global>::get<(samp::amx::AmxIdent, samp_sdk::amx::Amx), alloc::alloc::Global, hashbrown::map::equivalent_key::{closure_env#0}<samp::amx::AmxIdent, samp::amx::AmxIdent, samp_sdk::amx::Amx>> (self=0x81ffbec, hash=3136313669715300515, eq=...)
    at /cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/src/raw/mod.rs:831
#4  0xf596c474 in hashbrown::map::HashMap<samp::amx::AmxIdent, samp_sdk::amx::Amx, std::collections::hash::map::RandomState, alloc::alloc::Global>::get_inner<samp::amx::AmxIdent, samp_sdk::amx::Amx, std::collections::hash::map::RandomState, alloc::alloc::Global, samp::amx::AmxIdent> (self=0x81ffbdc, k=0xffffb4c8)
    at /cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/src/map.rs:1271
#5  0xf596c084 in hashbrown::map::HashMap<samp::amx::AmxIdent, samp_sdk::amx::Amx, std::collections::hash::map::RandomState, alloc::alloc::Global>::get<samp::amx::AmxIdent, samp_sdk::amx::Amx, std::collections::hash::map::RandomState, alloc::alloc::Global, samp::amx::AmxIdent> (self=0x81ffbdc, k=0xffffb4c8)
    at /cargo/registry/src/github.com-1285ae84e5963aae/hashbrown-0.12.3/src/map.rs:1223
#6  0xf596cd64 in std::collections::hash::map::HashMap<samp::amx::AmxIdent, samp_sdk::amx::Amx, std::collections::hash::map::RandomState>::get<samp::amx::AmxIdent, samp_sdk::amx::Amx, std::collections::hash::map::RandomState, samp::amx::AmxIdent> (self=0x81ffbdc, k=0xffffb4c8)
    at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/collections/hash/map.rs:881
#7  0xf59083e1 in samp::amx::get (ident=...)
    at /home/continue/.cargo/git/checkouts/samp-rs-4c9888f6d3249d70/2e91927/samp/src/amx.rs:48
#8  0xf58e62af in pawn_json::plugin::Plugin::__samp_native_json_stringify (amx=0x836fdd0, args=0xf4dfe1e8)
```

crashdetect log:

```

```

**Comment by continue98** [comment]
also I can't reproduce this problem on blank gamemode, but I tried to do it without other plugins (only pawn json was included), later I will try to include all the plugins that are used in the real gamemode

**Comment by Southclaws** [comment]
It looks like SSE is failing in a hash table library called hashbrown. I'm not really sure what the cause is from the trace though. Do you know if your target system is capable of 128 bit SSE registers?
